<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTswvsb3\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTswvsb3/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerTswvsb3.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerTswvsb3\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerTswvsb3\appProdProjectContainer([
    'container.build_hash' => 'Tswvsb3',
    'container.build_id' => 'e2226d5a',
    'container.build_time' => 1688339520,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTswvsb3');
